name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  paper_card:
    path: ../
  widget_mask: ^1.0.0+0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: badkhat
      fonts:
        - asset: assets/badkhat.ttf
    - family: darya
      fonts:
        - asset: assets/darya.ttf
    - family: paeez
      fonts:
        - asset: assets/paeez.ttf
    - family: shekari
      fonts:
        - asset: assets/shekari.ttf
    - family: khodkar
      fonts:
        - asset: assets/khodkar.ttf

